server:
 port: 8081
 
jdbc:
 driverClassName: com.mysql.cj.jdbc.Driver
 url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC
 user: <username>
 pass: <passowrd>

jwt:
 private-key:
  path: ./private-key

 
