server:
 port: 8080
 
zuul:
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  resource-service:
   path: /**/api/**
   url: http://localhost:8082
  oauth-service:
   path: /oauth/**
   url: http://localhost:8081
   stripPrefix: false

jwt:
 public-key:
  path: ./public-key

  
   
